import type { IconNode } from 'lucide';
import {
  Activity,
  Archive,
  ArchiveRestore,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  AtSign,
  BadgeCheck,
  Ban,
  Bell,
  BookOpen,
  Braces,
  Building,
  Calendar,
  CalendarClock,
  CalendarX,
  ChartColumn,
  ChartLine,
  ChartPie,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  CircleDot,
  CircleQuestionMark,
  CircleUser,
  CircleX,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Code,
  Columns3,
  Command,
  Compass,
  Copy,
  CopyPlus,
  Cpu,
  Crosshair,
  Database,
  Download,
  Earth,
  Ellipsis,
  EllipsisVertical,
  ExternalLink,
  Eye,
  EyeOff,
  FileCheck,
  FileClock,
  FilePen,
  FileSpreadsheet,
  FileText,
  FileUp,
  Flag,
  Forward,
  Gauge,
  Globe,
  GripHorizontal,
  GripVertical,
  Hand,
  Hash,
  HeartPulse,
  Hourglass,
  House,
  Import,
  Inbox,
  Info,
  KeyRound,
  Landmark,
  Laptop,
  Layers,
  LayoutGrid,
  Link,
  ListChecks,
  ListFilter,
  LoaderCircle,
  LocateFixed,
  Lock,
  LockOpen,
  LogOut,
  Mail,
  MailCheck,
  MailOpen,
  MailPlus,
  MailQuestion,
  MailX,
  Map,
  MapPin,
  MapPinned,
  MapPinPlus,
  Maximize,
  Megaphone,
  MemoryStick,
  Menu,
  Minimize,
  Minus,
  Monitor,
  Mountain,
  MousePointerClick,
  Navigation,
  OctagonX,
  PanelLeftClose,
  PanelLeftOpen,
  Paperclip,
  Pause,
  Pencil,
  Play,
  Plus,
  RefreshCw,
  Reply,
  RotateCcw,
  RotateCcwClock,
  Route,
  Rows3,
  Satellite,
  Scale,
  ScanSearch,
  ScrollText,
  Search,
  Send,
  Server,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Square,
  SquareSplitHorizontal,
  SquareTerminal,
  Stamp,
  Timer,
  Trash,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Type,
  Undo2,
  Upload,
  UserCheck,
  UserCog,
  UserMinus,
  UserPlus,
  UserRound,
  Users,
  UsersRound,
  UserX,
  Waypoints,
  Wifi,
  WifiOff,
  X,
  Zap,
} from 'lucide';

/**
 * Every icon the application draws, by the name templates use: `<svg lucideIcon="map-pin">`.
 *
 * Only what is imported here reaches the bundle, so an icon new to the app is added in two places:
 * the import and the map below.
 */
export const ICONS: Readonly<Record<string, IconNode>> = {
  'activity': Activity,
  'archive': Archive,
  'archive-restore': ArchiveRestore,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up-right': ArrowUpRight,
  'at-sign': AtSign,
  'badge-check': BadgeCheck,
  'ban': Ban,
  'bell': Bell,
  'book-open': BookOpen,
  'braces': Braces,
  'building': Building,
  'calendar': Calendar,
  'calendar-clock': CalendarClock,
  'calendar-x': CalendarX,
  'chart-column': ChartColumn,
  'chart-line': ChartLine,
  'chart-pie': ChartPie,
  'check': Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevrons-up-down': ChevronsUpDown,
  'chevron-up': ChevronUp,
  'circle-alert': CircleAlert,
  'circle-check': CircleCheck,
  'circle-dot': CircleDot,
  'circle-question-mark': CircleQuestionMark,
  'circle-user': CircleUser,
  'circle-x': CircleX,
  'clipboard-check': ClipboardCheck,
  'clipboard-list': ClipboardList,
  'clock': Clock,
  'code': Code,
  'columns-3': Columns3,
  'command': Command,
  'compass': Compass,
  'copy': Copy,
  'copy-plus': CopyPlus,
  'cpu': Cpu,
  'crosshair': Crosshair,
  'database': Database,
  'download': Download,
  'earth': Earth,
  'ellipsis': Ellipsis,
  'ellipsis-vertical': EllipsisVertical,
  'external-link': ExternalLink,
  'eye': Eye,
  'eye-off': EyeOff,
  'file-check': FileCheck,
  'file-clock': FileClock,
  'file-pen': FilePen,
  'file-spreadsheet': FileSpreadsheet,
  'file-text': FileText,
  'file-up': FileUp,
  'flag': Flag,
  'forward': Forward,
  'gauge': Gauge,
  'globe': Globe,
  'grip-horizontal': GripHorizontal,
  'grip-vertical': GripVertical,
  'hand': Hand,
  'hash': Hash,
  'heart-pulse': HeartPulse,
  'hourglass': Hourglass,
  'house': House,
  'import': Import,
  'inbox': Inbox,
  'info': Info,
  'key-round': KeyRound,
  'landmark': Landmark,
  'laptop': Laptop,
  'layers': Layers,
  'layout-grid': LayoutGrid,
  'link': Link,
  'list-checks': ListChecks,
  'list-filter': ListFilter,
  'loader-circle': LoaderCircle,
  'locate-fixed': LocateFixed,
  'lock': Lock,
  'lock-open': LockOpen,
  'log-out': LogOut,
  'mail': Mail,
  'mail-check': MailCheck,
  'mail-open': MailOpen,
  'mail-plus': MailPlus,
  'mail-question': MailQuestion,
  'mail-x': MailX,
  'map': Map,
  'map-pin': MapPin,
  'map-pinned': MapPinned,
  'map-pin-plus': MapPinPlus,
  'maximize': Maximize,
  'megaphone': Megaphone,
  'memory-stick': MemoryStick,
  'menu': Menu,
  'minimize': Minimize,
  'minus': Minus,
  'monitor': Monitor,
  'mountain': Mountain,
  'mouse-pointer-click': MousePointerClick,
  'navigation': Navigation,
  'octagon-x': OctagonX,
  'panel-left-close': PanelLeftClose,
  'panel-left-open': PanelLeftOpen,
  'paperclip': Paperclip,
  'pause': Pause,
  'pencil': Pencil,
  'play': Play,
  'plus': Plus,
  'refresh-cw': RefreshCw,
  'reply': Reply,
  'rotate-ccw': RotateCcw,
  'rotate-ccw-clock': RotateCcwClock,
  'route': Route,
  'rows-3': Rows3,
  'satellite': Satellite,
  'scale': Scale,
  'scan-search': ScanSearch,
  'scroll-text': ScrollText,
  'search': Search,
  'send': Send,
  'server': Server,
  'settings': Settings,
  'share-2': Share2,
  'shield': Shield,
  'shield-check': ShieldCheck,
  'sliders-horizontal': SlidersHorizontal,
  'smartphone': Smartphone,
  'sparkles': Sparkles,
  'square': Square,
  'square-split-horizontal': SquareSplitHorizontal,
  'square-terminal': SquareTerminal,
  'stamp': Stamp,
  'timer': Timer,
  'trash': Trash,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  'triangle-alert': TriangleAlert,
  'type': Type,
  'undo-2': Undo2,
  'upload': Upload,
  'user-check': UserCheck,
  'user-cog': UserCog,
  'user-minus': UserMinus,
  'user-plus': UserPlus,
  'user-round': UserRound,
  'users': Users,
  'users-round': UsersRound,
  'user-x': UserX,
  'waypoints': Waypoints,
  'wifi': Wifi,
  'wifi-off': WifiOff,
  'x': X,
  'zap': Zap,
};
